volumes:
  mongodb-snowstat-data:
    external: true
services:
  frontend:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /frontend_react
    volumes:
      - ./frontend_react:/frontend_react
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
  backend:
    build:
      context: ./backend_express
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - database
    environment:
      MONGODB_URL: mongodb://snowstats_admin.snowstat_sadmin.net:27017/snowstats_db
      WAIT_HOSTS: database:27017
      WAIT_TIMEOUT: 240
  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: snowstats_admin
      MONGO_INITDB_ROOT_PASSWORD: snowstat_sadmin
      MONGO_INITDB_DATABASE: snowstats_db
    ports:
      - 27017:27017
    volumes:
      - mongodb-snowstat-data:/data/db
